FROM node:14-alpine AS building
WORKDIR /app
COPY . /app
RUN npm cache clean --force && npm install
EXPOSE 4200 9876
RUN source .stage.env && npm run build


FROM nginx:1.21 AS production
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=building /app/dist/time-tracker /usr/share/nginx/html
EXPOSE 80

