FROM node:14

ENV USERNAME timetracker
ENV HOME /home/${USERNAME}
RUN useradd --create-home -ms /bin/bash ${USERNAME}

WORKDIR ${HOME}/time-tracker-ui
COPY package*.json ./
RUN chown ${USERNAME}:${USERNAME} -R ${HOME}/time-tracker-ui
RUN npm cache clean --force && npm install
COPY  --chown=${USERNAME}:${USERNAME} . .

USER ${USERNAME}
EXPOSE 4200
CMD ${HOME}/time-tracker-ui/node_modules/.bin/ng serve --host 0.0.0.0 --disableHostCheck=false --poll 2000