#!/bin/bash

> .env
echo 'AUTHORITY = '$AUTHORITY'' >> .env
echo 'CLIENT_ID = '$CLIENT_ID'' >> .env
echo 'SCOPES = '$SCOPES'' >> .env
echo 'STACK_EXCHANGE_ID = '$STACK_EXCHANGE_ID'' >> .env
echo 'STACK_EXCHANGE_ACCESS_TOKEN = '$STACK_EXCHANGE_ACCESS_TOKEN'' >> .env
echo 'AZURE_APP_CONFIGURATION_CONNECTION_STRING = '$AZURE_APP_CONFIGURATION_CONNECTION_STRING'' >> .env
cat .env
