# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CD process to deploy to App-Service service

on:
  # Trigger the workflow on pull request but only for the master branch
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout of master
      uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Inject Secrets
      shell: python
      env:
        SCOPES: ${{ secrets.scopes }}
        CLIENT_ID: ${{ secrets.client_id }}
        AUTHORITY: ${{ secrets.authority }}
        BASE_PATH: "src/environments/"
      run: |
        import os
        import json
        data = {}
        base_path = os.environ.get('BASE_PATH', 'src/environments/')
        with open(base_path + "keys.example.json", "r+") as jsonFileRead:
          data = json.load(jsonFileRead)
          data["scopes"] = str(os.environ['SCOPES']).split(",")
          data["client_id"] = os.environ['CLIENT_ID']
          data["authority"] = os.environ['AUTHORITY']
        with open(base_path + ".keys.json", "w+") as jsonFileWrite:
          json.dump(data, jsonFileWrite)

    - name: 'run: npm install and build'
      run: |
        npm install
        npm run build --prod --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'time-tracker-ui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_728dc744f9384bf38e8a0446aaaee29d }}
        package: dist/time-tracker
