name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone and checkout branch
      uses: actions/checkout@v2
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - run: npm run build --if-present
    - name: Run the test
      run: npm test
    - run: npm audit
      env:
        CI: true
