name: CI process for time-tracker app

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master

jobs:
  # security-audit:
  #   name: Running npm audit
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   steps:
  #     - name: Clone and checkout branch
  #       uses: actions/checkout@master

  #     - name: Set up Node.js version
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'

  #     # - name: Security Audit
  #     #   run: npm audit --audit-level=moderate

  ci-test:
    name: Unit tests and CodeCoverage
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    - name: Clone and checkout branch
      uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm install

    - name: Inject Secrets
      env:
        SCOPES: ${{ secrets.SCOPES }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        AUTHORITY: ${{ secrets.AUTHORITY }}
        STACK_EXCHANGE_ID: ${{ secrets.STACK_EXCHANGE_ID }}
        STACK_EXCHANGE_ACCESS_TOKEN: ${{ secrets.STACK_EXCHANGE_ACCESS_TOKEN }}
        AZURE_APP_CONFIGURATION_CONNECTION_STRING: ${{ secrets.AZURE_APP_CONFIGURATION_CONNECTION_STRING }}
      run: |
        chmod +x ./scripts/populate-keys.sh
        sh ./scripts/populate-keys.sh

    - name: Running tests
      run: npm run ci-test --if-present

    - name: Generate coverage report
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash)
