name: CI process for time-tracker app

on:
  # pull_request:
  #   types: [opened, edited, reopened, synchronize]
   push:
    branches:
      - 48-implement-semantic-version

jobs:

  ci-test:
    name: Running unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm install


    - name: Run Semantic-release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

